package com.intel.director.api;

public enum ImageInfoFields {

    NAME, IMAGE_DEPLOYMENTS, ID, IMAGE_FORMAT, CREATED_BY_USER_ID, CREATED_DATE, EDITED_BY_USER_ID, EDITED_DATE, STATUS, MOUNTED_BY_USER_ID,
    IMAGE_SIZE, SENT, LOCATION, DELETE, TRUST_POLICY_ID, TRUST_POLICY_NAME, TRUST_POLICY_DRAFT_ID, TRUST_POLICY_DRAFT_NAME
}
