package com.intel.director.api;

public enum ImageStoreUploadFields {

    ID, IMAGE_ID, TRUST_POLICY_ID, DATE, IMAGE_URI, CHECKSUM, TMP_LOCATION, STATUS, IMAGE_SIZE, SENT, UPLOADED_BY_USER_ID, IMAGE_NAME, IMAGE_FORMAT, IMAGE_DEPOLYMENT, IMAGE_CREATION_DATE
}
