package com.intel.director.api;

public enum ImageAttributeFields {

    NAME, IMAGE_DEPLOYMENTS, ID, IMAGE_FORMAT, CREATED_BY_USER_ID, CREATED_DATE, EDITED_BY_USER_ID, EDITED_DATE, STATUS, MOUNTED_BY_USER_ID,
    IMAGE_SIZE, SENT, LOCATION, DELETE
}
