package com.intel.director.api;

public enum TrustPolicyFields {

    NAME, ID, TRUST_POLICY, DESCRIPTION, CREATED_BY_USER_ID, CREATED_DATE, EDITED_BY_USER_ID, EDITED_DATE, IMAGE_NAME, IMAGE_FORMAT, IMAGE_DEPLOYMENT, IMAGE_CREATION_DATE
}
