package com.intel.director.api.ui;

public enum TrustPolicyDraftFields {

    NAME, ID, IMAGE_ID, TRUST_POLICY_DRAFT, CREATED_BY_USER_ID, CREATED_DATE, EDITED_BY_USER_ID, EDITED_DATE, IMAGE_NAME, IMAGE_FORMAT, IMAGE_DEPLOYMENT, IMAGE_CREATION_DATE
}
